apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      #securityContext:
        #fsGroup: 33
        #runAsUser: 33
        #runAsGroup: 33

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 3005

          volumeMounts:
            - name: audiobookshelf-data
              mountPath: /config
            - name: audiobookshelf-data
              mountPath: /metadata

          envFrom:
            - configMapRef:
                name: configenv

          #securityContext:
            #allowPrivilegeEscalation: false

      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc
