apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:o3OEGHnqCi/UjhCytosdpJ/NUUGdBghyaWzd0t3YOxdgz0entWT1pSa2tHuS04ULzSFM7kc9zaGxommZhfr1bGECKuDNRPxvBwpsofCJQBghgNFnXIhleWkE+izCfLQZoVYbL1HJnyLg/Mf+p529PeQNCTVlzjrv9ra7ng8MavxoSLSNSAw+Kf1ryiLXCjpRYhrvT0p3YXvd3NaobMDwkPrre4d5kNi7f44I4FEbQAf89hncXE3gc4mBp0II2GJZNgIQI4FQFsxCG8vMVAbvwMyiiLdUgmzfUE7p9sZpFN+QwHnrMxFW7AtZQFk=,iv:koDEkq53dMC2h6Du720AJbVAUZBafkaFEAntM0WVI1s=,tag:MzmpW4nLygwpeuzxoPwdsw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflare-tunnel-secret
sops:
    age:
        - recipient: age1s8ehrrlu5afq7d8662afjggvwysgawetfzu8svmpj8sjakv20qpsf4n5af
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZE83NWxxSVpFZG9pdHpV
            RlFCNk5za2tKMkhwdm5DRmE2Z3psc3BYamlvCmJpS2R3R1JLZnpSWDVQTlU2Qks4
            SUlGeUNXNkZJNXR6TW5jOC9TL2JjV3MKLS0tIE5uV3NkaFpYSWJSN0lrdjV3TmJ2
            eFQ4YisxOXNPck9JZW1yTU5wOEJoeTgK/isR/7ZasyVKYREOAKdmHgZuYjWd7597
            jHs+anJkRYRJctdtdHiGrLgnL+14dwtWok0QL2+rz5PkBmWR5RL9pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T23:57:22Z"
    mac: ENC[AES256_GCM,data:2W9bBEB4RdACyy3JtPoWQ/zM6+itmnhZWDUbjYcq0YEJ7r/lfWIUz7MqcoM6NKJg4Xy5QuQTFfr/pAillR8wbMduTc+MQw/1IAA1UJ0MHMaYygDnadtxG5aLVvPpn5lm/P1fX1P/P9hGOeRwXnu/VnbVUo20g79bNBMhW/YyYRU=,iv:IXZYnLvUDl1fXVO8iXzaycWX7NOMkS7+Ab2Ple57oPM=,tag:qiFQjHpByV9pQOQ+1EKKeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
