name: Trivy Test install

on:
  push:
    branches:
      - main

jobs:
  trivy-install:
    runs-on: ubuntu-latest
    steps:
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
          which trivy
