name: Trivy Image Scan

on:
  push:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy to scan for vulneralbilites
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'sissbruecker/linkding:1.44.0'
          format: 'table'
          exit-code: 1
          ignore-unfixed: 'true'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy for audiobookshelf image
        uses: aquasecurity/trivy-actions@master
        with:
          image-ref: 'ghcr.io/advplyr/audiobookshelf:latest'
          format: 'table'
          exit-code: 1
          ignore-unfixed: 'true'
          severity: 'CRITICAL, HIGH'
