name: Trivy Image Scan

on:
  push:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.18.3_Linux-64bit.deb

      - name: Define Images to scan
        id: images
        run: |
          echo "images=sissbruecker/linkding:1.44.0 ghcr.io/advplyr/audiobookshelf:latest" >> $GITHUB_OUTPUT

      - name: Scan Images
        run: |
          for image in ${{ steps.images.outputs.image }};do
            echo "Scanning image: $image"
            trivy image --severity HIGH,CRITICAL --format table $image
          done
